ALTER TABLE `hechos`
MODIFY COLUMN `tipo_hecho` ENUM(
    'VOLCADURA',
    'SALIDA DE SUPERFICIE DE RODAMIENTO',
    'SUBIDA AL CAMELLÓN',
    'CAIDA DE MOTOCICLETA',
    'COLISIÓN CON PEATÓN',
    'COLISIÓN POR ALCANCE',
    'COLISIÓN POR NO RESPETAR SEMÁFORO',
    'COLISIÓN POR INVASIÓN DE CARRIL',
    'COLISIÓN POR CAMBIO DE CARRIL',
    'COLISIÓN POR CORTE DE CIRCULACIÓN',
    'COLISIÓN CONTRA SEMOVIENTE',
    'COLISIÓN POR MANIOBRA DE REVERSA',
    'COLISIÓN CONTRA OBJETO FIJO',
    'CAIDA ACUATICA DE VEHÍCULO',
    'DESBARRANCAMIENTO',
    'INCENDIO',
    'EXPLOSIÓN',
    'Otro'
) NOT NULL;
