<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class AddColisionContraSemovienteToHechosTipoHecho extends Migration
{
    private const TIPO_HECHO_CON_SEMOVIENTE = "ENUM('VOLCADURA','SALIDA DE SUPERFICIE DE RODAMIENTO','SUBIDA AL CAMELLÓN','CAIDA DE MOTOCICLETA','COLISIÓN CON PEATÓN','COLISIÓN POR ALCANCE','COLISIÓN POR NO RESPETAR SEMÁFORO','COLISIÓN POR INVASIÓN DE CARRIL','COLISIÓN POR CAMBIO DE CARRIL','COLISIÓN POR CORTE DE CIRCULACIÓN','COLISIÓN CONTRA SEMOVIENTE','COLISIÓN POR MANIOBRA DE REVERSA','COLISIÓN CONTRA OBJETO FIJO','CAIDA ACUATICA DE VEHÍCULO','DESBARRANCAMIENTO','INCENDIO','EXPLOSIÓN','Otro')";

    private const TIPO_HECHO_SIN_SEMOVIENTE = "ENUM('VOLCADURA','SALIDA DE SUPERFICIE DE RODAMIENTO','SUBIDA AL CAMELLÓN','CAIDA DE MOTOCICLETA','COLISIÓN CON PEATÓN','COLISIÓN POR ALCANCE','COLISIÓN POR NO RESPETAR SEMÁFORO','COLISIÓN POR INVASIÓN DE CARRIL','COLISIÓN POR CAMBIO DE CARRIL','COLISIÓN POR CORTE DE CIRCULACIÓN','COLISIÓN POR MANIOBRA DE REVERSA','COLISIÓN CONTRA OBJETO FIJO','CAIDA ACUATICA DE VEHÍCULO','DESBARRANCAMIENTO','INCENDIO','EXPLOSIÓN','Otro')";

    public function up(): void
    {
        DB::statement('ALTER TABLE `hechos` MODIFY COLUMN `tipo_hecho` ' . self::TIPO_HECHO_CON_SEMOVIENTE . ' NOT NULL');
    }

    public function down(): void
    {
        DB::table('hechos')
            ->where('tipo_hecho', 'COLISIÓN CONTRA SEMOVIENTE')
            ->update(['tipo_hecho' => 'COLISIÓN POR CORTE DE CIRCULACIÓN']);

        DB::statement('ALTER TABLE `hechos` MODIFY COLUMN `tipo_hecho` ' . self::TIPO_HECHO_SIN_SEMOVIENTE . ' NOT NULL');
    }
}
