<?php

return [
    'catalogos' => [
        'sectores' => [
            'REVOLUCION' => 'REVOLUCIÓN',
            'NUEVA ESPANA' => 'NUEVA ESPAÑA',
            'INDEPENDENCIA' => 'INDEPENDENCIA',
            'REPUBLICA' => 'REPÚBLICA',
            'CENTRO' => 'CENTRO',
        ],
        'tipos_hecho' => [
            'VOLCADURA' => 'VOLCADURA',
            'INCIDENTE DE TRANSITO' => 'INCIDENTE DE TRÁNSITO',
            'SALIDA DE SUPERFICIE DE RODAMIENTO' => 'SALIDA DE SUPERFICIE DE RODAMIENTO',
            'SUBIDA AL CAMELLON' => 'SUBIDA AL CAMELLÓN',
            'CAIDA DE MOTOCICLETA' => 'CAIDA DE MOTOCICLETA',
            'COLISION CON PEATON' => 'COLISIÓN CON PEATÓN',
            'COLISION POR ALCANCE' => 'COLISIÓN POR ALCANCE',
            'COLISION POR NO RESPETAR SEMAFORO' => 'COLISIÓN POR NO RESPETAR SEMÁFORO',
            'COLISION POR INVASION DE CARRIL' => 'COLISIÓN POR INVASIÓN DE CARRIL',
            'COLISION POR CORTE DE CIRCULACION' => 'COLISIÓN POR CORTE DE CIRCULACIÓN',
            'COLISION POR CAMBIO DE CARRIL' => 'COLISIÓN POR CAMBIO DE CARRIL',
            'COLISION POR MANIOBRA DE REVERSA' => 'COLISIÓN POR MANIOBRA DE REVERSA',
            'COLISION CONTRA OBJETO FIJO' => 'COLISIÓN CONTRA OBJETO FIJO',
            'COLISION CONTRA SEMOVIENTE' => 'COLISIÓN CONTRA SEMOVIENTE',
            'CAIDA ACUATICA DE VEHICULO' => 'CAIDA ACUATICA DE VEHÍCULO',
            'DESBARRANCAMIENTO' => 'DESBARRANCAMIENTO',
            'INCENDIO' => 'INCENDIO',
            'EXPLOSION' => 'EXPLOSIÓN',
        ],
        'superficies_via' => [
            'ASFALTO' => 'Asfalto',
            'CONCRETO' => 'Concreto',
            'ADOQUIN' => 'Adoquín',
            'TERRACERIA' => 'Terracería',
            'EMPEDRADO' => 'Empedrado',
            'GRAVA' => 'Grava',
        ],
        'tiempos' => [
            'DIA' => 'Día',
            'NOCHE' => 'Noche',
            'AMANECER' => 'Amanecer',
            'ATARDECER' => 'Atardecer',
        ],
        'climas' => [
            'BUENO' => 'Bueno',
            'MALO' => 'Malo',
            'NUBLADO' => 'Nublado',
            'LLUVIOSO' => 'Lluvioso',
        ],
        'condiciones' => [
            'BUENO' => 'Bueno',
            'REGULAR' => 'Regular',
            'MALO' => 'Malo',
        ],
        'controles_transito' => [
            'SEMAFORO' => 'Semáforo',
            'SENALAMIENTO VERTICAL' => 'Señalamiento vertical',
            'MARCA VIAL' => 'Marca vial',
            'AGENTE DE TRANSITO' => 'Agente de tránsito',
            'REDUCTOR DE VELOCIDAD' => 'Reductor de velocidad',
            'GLORIETA' => 'Glorieta',
            'NINGUNO' => 'Ninguno',
        ],
        'causas' => [
            'VELOCIDAD MAYOR DE LA PERMITIDA' => 'Velocidad mayor de la permitida',
            'NO CONSERVAR DISTANCIA' => 'No conservar distancia',
            'CORTE DE CIRCULACION' => 'Corte de circulación',
            'INVASION DE CARRIL' => 'Invasión de carril',
            'NO RESPETAR SEMAFORO' => 'No respetar semáforo',
            'MANIOBRA DE REVERSA' => 'Maniobra de reversa',
            'DERECHO DE VIA' => 'Derecho de vía',
            'NO ASEGURAR VEHICULO' => 'No asegurar vehículo',
            'CAMBIO DE CARRIL' => 'Cambio de carril',
            'FALLA MECANICA' => 'Falla mecánica',
            'CONDICIONES DE LA VIA' => 'Condiciones de la vía',
            'NO CALCULAR DIMENSIONES' => 'No calcular dimensiones',
            'PERDIDA DE CONTROL' => 'Pérdida de control',
            'NO CEDER EL PASO AL PEATON' => 'No ceder el paso al peatón',
        ],
        'responsables' => [
            'VEHICULO A' => 'Vehículo A',
            'VEHICULO B' => 'Vehículo B',
            'VEHICULO C' => 'Vehículo C',
            'VEHICULO D' => 'Vehículo D',
            'VEHICULO E' => 'Vehículo E',
            'VEHICULO F' => 'Vehículo F',
        ],
        'colisiones_camino' => [
            'VEHICULOS' => 'Vehículos',
            'SEMOVIENTES' => 'Semovientes',
            'OBJETO FIJO' => 'Objeto fijo',
            'PEATON' => 'Peatón',
            'BICICLETA' => 'Bicicleta',
        ],
        'situaciones' => [
            'RESUELTO' => 'RESUELTO',
            'PENDIENTE' => 'PENDIENTE',
            'TURNADO' => 'TURNADO',
            'REPORTE' => 'REPORTE',
        ],
    ],
];
