<?php

$marcas = [
    'ABARTH', 'ACURA', 'AJP', 'ALFA ROMEO', 'ALSTOM', 'AION', 'AKT', 'ANKAI', 'APRILIA', 'ARCFOX',
    'AITO', 'ATRO', 'AUDI', 'AVATR', 'BAIC', 'BAJAJ', 'BENDA', 'BENTLEY', 'BENELLI', 'BETA',
    'BENOTTO', 'BIANCHI', 'BIMOTA', 'BMW', 'BOBCAT', 'BOMBARDIER', 'BRILLIANCE', 'BUICK', 'BYD',
    'CADILLAC', 'CAF', 'CAN-AM', 'CANNONDALE', 'CARABELA', 'CASE', 'CATERPILLAR', 'CFMOTO', 'CHANGAN',
    'CHERY', 'CHEVROLET', 'CHIREY', 'CHRYSLER', 'CIMC', 'CITROEN', 'CLARK', 'CLEVELAND CYCLEWERKS',
    'CROWN', 'CRRC', 'CUBE', 'CUPRA', 'DACIA', 'DAF', 'DAIHATSU', 'DAYUN', 'DEEPAL', 'DENZA', 'DFSK',
    'DINA', 'DINAMO', 'DODGE', 'DONGFENG', 'DOOSAN', 'DS', 'DUCATI', 'EXEED', 'EXLANTIX', 'EMD',
    'FAW', 'FARIZON', 'FERRARI', 'FIAT', 'FONTAINE', 'FORD', 'FOTON', 'FREIGHTLINER', 'FORTHING',
    'FRUEHAUF', 'FUSO', 'GASGAS', 'GAC', 'GE', 'GEELY', 'GENESIS', 'GENIE', 'GIANT', 'GMC',
    'GOLDEN DRAGON', 'GREAT DANE', 'GREAT WALL', 'GT', 'GWM', 'HARLEY-DAVIDSON', 'HAVAL', 'HERO',
    'HINO', 'HITACHI', 'HIGER', 'HONDA', 'HONGQI', 'HUFFY', 'HUMMER', 'HUSQVARNA', 'HYSTER',
    'HYUNDAI', 'HYUNDAI TRANSLEAD', 'INDIAN', 'INFINITI', 'INTERNATIONAL', 'ISUZU', 'ISLO', 'ITALIKA',
    'IVECO', 'IZUKA', 'ICAR', 'JAC', 'JAECOO', 'JAGUAR', 'JCB', 'JEEP', 'JETOUR', 'JIALING', 'JMC',
    'JLG', 'JOHN DEERE', 'KANSAS CITY SOUTHERN', 'KAWASAKI', 'KAIYI', 'KARRY', 'KEEWAY', 'KENWORTH',
    'KIA', 'KOMATSU', 'KTM', 'KOVE', 'KUBOTA', 'KURAZAI', 'KYMCO', 'LAMBORGHINI', 'LAND ROVER',
    'LEAPMOTOR', 'LEPAS', 'LEXUS', 'LIEBHERR', 'LIFAN', 'LINCOLN', 'LIUGONG', 'LONCIN', 'LOZANO',
    'LUFKIN', 'LUXEED', 'LYNK & CO', 'MACK', 'MAN', 'MANITOU', 'MASERATI', 'MAZDA', 'MAXUS',
    'MB MOTORS', 'MERCEDES-BENZ', 'MERCURY', 'MERIDA', 'MG', 'MINI', 'MOBILITY ADO', 'MITSUBISHI',
    'MONGOOSE', 'MOTO GUZZI', 'MOTO MORINI', 'MV AGUSTA', 'NAVISTAR', 'NETA', 'NEW HOLLAND', 'NIO',
    'NISSAN', 'NO APLICA', 'OLDSMOBILE', 'OMODA', 'ORA', 'OPEL', 'ORBEA', 'PETERBILT', 'PEUGEOT',
    'PIAGGIO', 'PLYMOUTH', 'POLARIS', 'POLESTAR', 'PONTIAC', 'PORSCHE', 'QJMOTOR', 'RALEIGH', 'RADAR',
    'RAM', 'REA', 'RENAULT', 'RIVIAN', 'ROYAL ENFIELD', 'SAAB', 'SANY', 'SATURN', 'SCANIA', 'SCION',
    'SCOTT', 'SDLG', 'SENKE', 'SERES', 'SEAT', 'SHACMAN', 'SHINERAY', 'SIEMENS', 'SINOTRUK', 'SITRAK',
    'SKODA', 'SKYJACK', 'SKYWORTH', 'SMART', 'SPECIALIZED', 'STERLING', 'STOUGHTON', 'SUBARU',
    'SUNLONG', 'SUZUKI', 'SWM', 'SYM', 'TANK', 'TEREX', 'TESLA', 'TOYOTA', 'TRAILMOBILE', 'TREK',
    'TREMAC', 'TRIUMPH', 'TVS', 'UD TRUCKS', 'UTILITY', 'VENTO', 'VESPA', 'VELOCI', 'VICTORY',
    'VINFAST', 'VOGE', 'VOLKSWAGEN', 'VOLVO', 'WABASH', 'WABTEC', 'WEY', 'WULING', 'WESTERN STAR',
    'WILSON', 'WINMEX', 'XCMG', 'XPENG', 'YANGWANG', 'YALE', 'YAMAHA', 'YUTONG', 'ZANELLA', 'ZEEKR',
    'ZHONGTONG', 'ZONGSHEN', 'ZONTES',
];

return [
    'catalogos' => [
        'tipos_generales' => [
            'automovil' => 'Automóvil',
            'camioneta' => 'Camioneta',
            'camion' => 'Camión',
            'motocicleta' => 'Motocicleta',
            'bicicleta' => 'Bicicleta',
            'remolque' => 'Remolque',
            'maquinaria' => 'Maquinaria',
            'tren' => 'Tren',
            'semoviente' => 'Semoviente',
        ],
        'carrocerias' => [
            'automovil' => ['Sedán', 'Hatchback', 'Coupé', 'SUV', 'Convertible'],
            'camioneta' => ['Pick-up', 'Panel', 'Vagoneta', 'Furgoneta', 'Van'],
            'camion' => ['Caja seca', 'Caja cerrada', 'Caja abierta', 'Plataforma', 'Volteo', 'Refrigerado', 'Cisterna', 'Pipa', 'Grúa', 'Torton', 'Rabón', 'Tracto', 'Redilas', 'Autobús'],
            'motocicleta' => ['Trabajo', 'Cruiser', 'Doble Propósito', 'Scooter', 'Enduro', 'Naked', 'Pista', 'Chopper', 'Cuatrimoto'],
            'bicicleta' => ['Montaña', 'Ruta', 'BMX', 'Urbana', 'Plegable'],
            'remolque' => ['Plataforma', 'Caja cerrada', 'Caja seca', 'Cama baja', 'Refrigerado', 'Volteo', 'Góndola', 'Dolly', 'Portacontenedor'],
            'maquinaria' => ['Retroexcavadora', 'Excavadora', 'Cargador frontal', 'Motoconformadora', 'Bulldozer', 'Rodillo compactador', 'Grúa industrial', 'Montacargas', 'Tractor agrícola', 'Pavimentadora', 'Compactadora'],
            'tren' => ['Locomotora', 'Vagón', 'Tren de carga', 'Tren de pasajeros', 'Tranvía', 'Metro'],
            'semoviente' => ['Caballo', 'Burro', 'Vaca', 'Mula', 'Otro animal de tiro'],
        ],
        'marcas' => array_combine($marcas, $marcas),
        'colores' => array_combine($colores = [
            'Blanco', 'Blanco perla', 'Negro', 'Gris', 'Gris Oxford', 'Plata', 'Rojo', 'Vino', 'Azul',
            'Azul marino', 'Verde', 'Verde oscuro', 'Arena', 'Beige', 'Café', 'Dorado', 'Naranja',
            'Amarillo', 'Morado', 'Rosa', 'Guinda', 'Bronce', 'Champagne',
        ], $colores),
        'aseguradoras' => array_combine($aseguradoras = [
            'Qualitas', 'GNP', 'AXA', 'Banorte', 'HDI', 'Mapfre', 'Zurich', 'BBVA', 'Afirme', 'Inbursa',
            'Chubb', 'Potosí', 'General de Seguros', 'Povet', 'Atlas', 'GOA', 'ANA', 'Primero Seguros',
            'Miituo', 'AIG', 'Insignia Life', 'Thona Seguros', 'Ve por Más Seguros (BX+)',
        ], $aseguradoras),
        'tipos_servicio' => array_combine($servicios = [
            'PARTICULAR', 'SERVICIO PÚBLICO ESTATAL', 'SERVICIO PÚBLICO FEDERAL', 'OFICIAL',
        ], $servicios),
        'estados_placas' => [
            'AGUASCALIENTES' => 'Aguascalientes', 'BAJACALIFORNIA' => 'Baja California',
            'BAJACALIFORNIASUR' => 'Baja California Sur', 'CAMPECHE' => 'Campeche', 'CHIAPAS' => 'Chiapas',
            'CHIHUAHUA' => 'Chihuahua', 'CIUDADDEMEXICO' => 'Ciudad de México', 'COAHUILA' => 'Coahuila',
            'COLIMA' => 'Colima', 'DURANGO' => 'Durango', 'GUANAJUATO' => 'Guanajuato', 'GUERRERO' => 'Guerrero',
            'HIDALGO' => 'Hidalgo', 'JALISCO' => 'Jalisco', 'MEXICO' => 'Estado de México',
            'MICHOACAN' => 'Michoacán', 'MORELOS' => 'Morelos', 'NAYARIT' => 'Nayarit',
            'NUEVOLEON' => 'Nuevo León', 'OAXACA' => 'Oaxaca', 'PUEBLA' => 'Puebla',
            'QUERETARO' => 'Querétaro', 'QUINTANAROO' => 'Quintana Roo',
            'SANLUISPOTOSI' => 'San Luis Potosí', 'SINALOA' => 'Sinaloa', 'SONORA' => 'Sonora',
            'TABASCO' => 'Tabasco', 'TAMAULIPAS' => 'Tamaulipas', 'TLAXCALA' => 'Tlaxcala',
            'VERACRUZ' => 'Veracruz', 'YUCATAN' => 'Yucatán', 'ZACATECAS' => 'Zacatecas',
            'CALIFORNIAUSA' => 'California (EUA)', 'ARIZONAUSA' => 'Arizona (EUA)',
            'NUEVOMEXICOUSA' => 'Nuevo México (EUA)', 'TEXASUSA' => 'Texas (EUA)',
        ],
    ],
];
